// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QiskitPlayground) DeepCopyInto(out *QiskitPlayground) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QiskitPlayground.
func (in *QiskitPlayground) DeepCopy() *QiskitPlayground {
	if in == nil {
		return nil
	}
	out := new(QiskitPlayground)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QiskitPlayground) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QiskitPlaygroundList) DeepCopyInto(out *QiskitPlaygroundList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QiskitPlayground, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QiskitPlaygroundList.
func (in *QiskitPlaygroundList) DeepCopy() *QiskitPlaygroundList {
	if in == nil {
		return nil
	}
	out := new(QiskitPlaygroundList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QiskitPlaygroundList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QiskitPlaygroundSpec) DeepCopyInto(out *QiskitPlaygroundSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QiskitPlaygroundSpec.
func (in *QiskitPlaygroundSpec) DeepCopy() *QiskitPlaygroundSpec {
	if in == nil {
		return nil
	}
	out := new(QiskitPlaygroundSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QiskitPlaygroundStatus) DeepCopyInto(out *QiskitPlaygroundStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QiskitPlaygroundStatus.
func (in *QiskitPlaygroundStatus) DeepCopy() *QiskitPlaygroundStatus {
	if in == nil {
		return nil
	}
	out := new(QiskitPlaygroundStatus)
	in.DeepCopyInto(out)
	return out
}
